# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vnnpaper',
                'doc_host': 'https://DanielKick-USDA.github.io',
                'git_url': 'https://github.com/DanielKick-USDA/vnnpaper',
                'lib_path': 'vnnpaper'},
  'syms': {'vnnpaper.core': {'vnnpaper.core.foo': ('core.html#foo', 'vnnpaper/core.py')}}}
